### ISSUE TITLE
Bug in command parsing

### ISSUE THREAD

**Issue by mrquincle** [Kvanr23/CrownstoneTestSuite#1]
Just basic command like:

```python3 Switching.py -a 'C2:81:75:46:D8:F1' ```

Leads to error:

```
Traceback (most recent call last):
  File "Switching.py", line 262, in <module>
    if out_folder:
NameError: name 'out_folder' is not defined
```

**Comment by Kvanr23** [comment]
Fixed in release [v0.0.2](https://github.com/Kvanr23/CrownstoneTestSuite/releases/tag/V0.0.2)
