### ISSUE TITLE
Recommend setting cap on bluepy-helper, not sudo

### ISSUE THREAD

**Issue by mrquincle** [Kvanr23/CrownstoneTestSuite#2]
Do not tell people to run sudo strace your command.

Tell them to set capability on bluepy-helper (required for scanning):

```
sudo setcap 'cap_net_raw,cap_net_admin+eip' wherever-they-installed/bluepy-helper
```

**Comment by Kvanr23** [comment]
Added info for this [here](https://github.com/Kvanr23/CrownstoneTestSuite/blob/main/PROCEDURE.md#sudo-rights-for-bluepy-helper)
