### ISSUE TITLE
Searching by default for MAC address starting with EC?

### ISSUE THREAD

**Issue by mrquincle** [Kvanr23/CrownstoneTestSuite#3]
A very weird default which also needlessly requires scanning capabilities. The default should be to tell people to fill in an address. Only if you indicate something like a `-scan` option, you might support that. However, also in that case you might perhaps want to filter on RSSI. Specifying the MAC address is much more reliable though.

**Comment by Kvanr23** [comment]
Fixed in release [v0.0.2](https://github.com/Kvanr23/CrownstoneTestSuite/releases/tag/V0.0.2)
